#if !canImport(ObjectiveC)
import XCTest

extension EthereumWeb3Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EthereumWeb3Tests = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EthereumWeb3Tests.__allTests__EthereumWeb3Tests),
    ]
}
#endif
